spring:
  application:
    name: worker
  config:
    enabled: true
    import: optional:configserver:http://localhost:8088
   
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    